<a href="https://colab.research.google.com/github/Gabriel-Feang/Gabriel-Feang/blob/main/NumpyTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
A + [5]

array([6, 7, 8])

In [14]:
A + np.array([4,6])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

multiply a list = repeat its contents, multiplying the N of the list
x
multiply an vector = actually performing multiplication on all elements

In [16]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
2*A

array([2, 4, 6])

In [18]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
A + A

array([2, 4, 6])

In [21]:
L2 = []
for e in L:
  L2.append(e + 3)

In [22]:
L2

[4, 5, 6, 7]